# Generated by Django 5.0.2 on 2024-03-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('birth_date', models.DateField(null=True)),
                ('division', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_crud.student')),
            ],
        ),
    ]
