# Generated by Django 5.0.2 on 2024-03-08 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0002_studentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='user_crud.student'),
        ),
    ]
