# Generated by Django 4.2.3 on 2024-03-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_crud', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
